version: 1.0.{build}
cache:
  - C:/Tools/vcpkg -> appveyor.yml
build_script:
- cmd: >-
    vcpkg install qt5-base
    if not exist "build" mkdir "build"
    cd build
    cmake ..
    msbuild qt-ini-edit.sln
    cd ..
